# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='ex',
        ),
        migrations.AddField(
            model_name='ask',
            name='date',
            field=models.CharField(default='000', max_length=30, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='a',
            field=models.CharField(default='222', max_length=30, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='link',
            field=models.CharField(default='222', max_length=30, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='q',
            field=models.CharField(default='222', max_length=30, verbose_name='q'),
        ),
    ]
