# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(default='222', max_length=30, verbose_name='q')),
                ('a', models.CharField(default='222', max_length=30, verbose_name='a')),
                ('link', models.CharField(default='222', max_length=30, verbose_name='link')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('choice', models.BooleanField(verbose_name='choice')),
                ('myfile', models.FileField(upload_to='myfile', verbose_name='myfile')),
                ('myimg', models.ImageField(upload_to='img', verbose_name='myimg')),
            ],
        ),
    ]
