# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201104_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u4efb\u52a1'},
        ),
    ]
